services:
  - type: web
    name: your-app-name
    runtime: python
    buildCommand: |
      apt-get update
      apt-get install -y tesseract-ocr libtesseract-dev
      pip install -r requirements.txt
    startCommand: python app.py
